### ISSUE TITLE
Change default password

### ISSUE THREAD

**Issue by bernardino** [equinor/helm-charts#6]
The warning section in the `README` describing how we need to delete the pvc to change the default password is not correct.

We can indeed reset that password without having to delete the PVC by:
1. Deleting the file `/var/lib/neo4j/data/dbms/auth`
2. Running `neo4j-admin set-initial-password <new password>`
3. Deleting the pod / restart the service

I will create a PR with this section updated.

**Comment by Subreptivus** [comment]
Fixed by: https://github.com/equinor/helm-charts/pull/7
